development:
  adapter: postgresql
  database: ticketee_development
  username: emerak
  password: 51234

test:
  adapter: postgresql
  database: ticketee_test
  username:  emerak
  password:  12345

production:
  adapter:  postgresql
  database: ticketee_production 
  username: emerak 
  password: 12345
